import {
  createCylindricalCanSequence,
  createGlossyPhoneSequence,
  createLabelBottleSequence,
  createPlanarBookSequence,
  createRigidBoxSequence,
  createSnackPouchSequence,
  createTexturedCupSequence,
} from './visionFixtures.js';

export const defaultReplayScenarios = [
  {
    name: 'planar book on desk',
    create: () => createPlanarBookSequence({
      kind: 'planar-book',
      frameCount: 32,
      occlusionFrames: [14, 15, 16, 17],
    }),
  },
  {
    name: 'dark book on desk',
    create: () => createPlanarBookSequence({
      kind: 'dark-book',
      frameCount: 32,
      occlusionFrames: [14, 15, 16, 17],
    }),
  },
  {
    name: 'depth book on desk',
    create: () => createPlanarBookSequence({
      kind: 'depth-book',
      frameCount: 36,
      occlusionFrames: [18, 19, 20],
    }),
  },
  {
    name: 'cylindrical can on desk',
    create: () => createCylindricalCanSequence({
      frameCount: 30,
      occlusionFrames: [12, 13, 14],
    }),
  },
  {
    name: 'tapered cup on desk',
    create: () => createTexturedCupSequence({
      frameCount: 32,
      occlusionFrames: [15, 16, 17],
    }),
  },
  {
    name: 'rigid box on desk',
    create: () => createRigidBoxSequence({
      frameCount: 28,
      occlusionFrames: [10, 11, 12],
    }),
  },
];

export const realisticReplayScenarios = [
  {
    name: 'book cover with early occlusion on busy moving background',
    create: () => createPlanarBookSequence({
      kind: 'planar-book',
      frameCount: 36,
      occlusionFrames: [9, 10, 24],
      backgroundVariant: 'busy',
      backgroundSeed: 71,
    }),
    limits: {
      maxAnchorError: 22,
      meanAnchorError: 10,
      maxScaleError: 0.12,
      maxFrameJump: 12,
      maxRotationError: 0.8,
      maxWorldPositionError: 0.16,
      maxScaleLogError: 0.15,
      maxHeadJumpExcess: 0.05,
    },
  },
  {
    name: 'dark book cover on shelf background',
    create: () => createPlanarBookSequence({
      kind: 'dark-book',
      frameCount: 34,
      occlusionFrames: [8, 9, 22],
      backgroundVariant: 'shelf',
      backgroundSeed: 83,
    }),
    limits: {
      maxAnchorError: 16,
      meanAnchorError: 8.5,
      maxScaleError: 0.11,
      maxFrameJump: 10,
      maxRotationError: 0.55,
      maxWorldPositionError: 0.12,
      maxScaleLogError: 0.11,
      maxHeadJumpExcess: 0.055,
    },
  },
  {
    name: 'depth book with repeated occlusion on busy moving background',
    create: () => createPlanarBookSequence({
      kind: 'depth-book',
      frameCount: 40,
      occlusionFrames: [8, 9, 27, 28],
      backgroundVariant: 'busy',
      backgroundSeed: 91,
    }),
    limits: {
      maxAnchorError: 21,
      meanAnchorError: 10,
      maxScaleError: 0.14,
      maxFrameJump: 12,
      maxRotationError: 1.2,
      maxWorldPositionError: 0.16,
      maxScaleLogError: 0.23,
      maxHeadJumpExcess: 0.055,
    },
  },
  {
    name: 'cylindrical can with repeated occlusion on shelf background',
    create: () => createCylindricalCanSequence({
      frameCount: 34,
      occlusionFrames: [8, 9, 22],
      backgroundVariant: 'shelf',
      backgroundSeed: 101,
    }),
    limits: {
      maxAnchorError: 15,
      meanAnchorError: 6,
      maxScaleError: 0.17,
      maxFrameJump: 12,
      maxRotationError: 0.95,
      maxWorldPositionError: 0.11,
      maxScaleLogError: 0.18,
      maxHeadJumpExcess: 0.065,
    },
    limitsByMode: {
      'parametric-surface': {
        maxAnchorError: 15,
        meanAnchorError: 6,
        maxScaleError: 0.17,
        maxFrameJump: 12,
        maxRotationError: 1.9,
        maxWorldPositionError: 0.12,
        maxScaleLogError: 0.18,
        maxHeadJumpExcess: 0.065,
      },
      'direct-photometric': {
        maxAnchorError: 15,
        meanAnchorError: 6,
        maxScaleError: 0.17,
        maxFrameJump: 12,
        maxRotationError: 1.9,
        maxWorldPositionError: 0.12,
        maxScaleLogError: 0.18,
        maxHeadJumpExcess: 0.065,
      },
    },
  },
  {
    name: 'tapered cup with early repeated occlusion on busy moving background',
    create: () => createTexturedCupSequence({
      frameCount: 36,
      occlusionFrames: [10, 11, 24],
      backgroundVariant: 'busy',
      backgroundSeed: 111,
    }),
    limits: {
      maxAnchorError: 22,
      meanAnchorError: 14,
      maxScaleError: 0.17,
      maxFrameJump: 12,
      maxRotationError: 1.35,
      maxWorldPositionError: 0.16,
      maxScaleLogError: 0.15,
      maxHeadJumpExcess: 0.08,
    },
    limitsByMode: {
      'parametric-surface': {
        maxAnchorError: 25,
        meanAnchorError: 14,
        maxScaleError: 0.17,
        maxFrameJump: 12,
        maxRotationError: 1.35,
        maxWorldPositionError: 0.19,
        maxScaleLogError: 0.15,
        maxHeadJumpExcess: 0.08,
      },
      'direct-photometric': {
        maxAnchorError: 25,
        meanAnchorError: 14,
        maxScaleError: 0.17,
        maxFrameJump: 12,
        maxRotationError: 1.35,
        maxWorldPositionError: 0.19,
        maxScaleLogError: 0.15,
        maxHeadJumpExcess: 0.08,
      },
    },
  },
  {
    name: 'tapered cup with late occlusion on shelf background',
    create: () => createTexturedCupSequence({
      frameCount: 28,
      occlusionFrames: [18, 19],
      backgroundVariant: 'shelf',
      backgroundSeed: 121,
    }),
    limits: {
      maxAnchorError: 27,
      meanAnchorError: 10,
      maxScaleError: 0.26,
      maxFrameJump: 12,
      maxRotationError: 1.15,
      maxWorldPositionError: 0.21,
      maxScaleLogError: 0.25,
      maxHeadJumpExcess: 0.07,
    },
    limitsByMode: {
      'parametric-surface': {
        maxAnchorError: 30,
        meanAnchorError: 10,
        maxScaleError: 0.26,
        maxFrameJump: 12,
        maxRotationError: 1.15,
        maxWorldPositionError: 0.23,
        maxScaleLogError: 0.25,
        maxHeadJumpExcess: 0.07,
      },
      'direct-photometric': {
        maxAnchorError: 30,
        meanAnchorError: 10,
        maxScaleError: 0.26,
        maxFrameJump: 12,
        maxRotationError: 1.15,
        maxWorldPositionError: 0.23,
        maxScaleLogError: 0.25,
        maxHeadJumpExcess: 0.07,
      },
    },
  },
  {
    name: 'glossy phone with glare near window background',
    create: () => createGlossyPhoneSequence({
      frameCount: 24,
      occlusionFrames: [8, 17],
      backgroundVariant: 'window',
      backgroundSeed: 67,
    }),
    limits: {
      maxAnchorError: 21,
      meanAnchorError: 10,
      maxScaleError: 0.12,
      maxFrameJump: 12,
      maxRotationError: 1.15,
      maxWorldPositionError: 0.16,
      maxScaleLogError: 0.12,
      maxHeadJumpExcess: 0.065,
    },
    surfaceByMode: {
      'parametric-surface': 'plane',
      'direct-photometric': 'photometric-surfels',
    },
  },
  {
    name: 'label bottle on kitchen tile background',
    create: () => createLabelBottleSequence({
      frameCount: 24,
      occlusionFrames: [7, 16],
      backgroundVariant: 'kitchen',
      backgroundSeed: 79,
    }),
    limits: {
      maxAnchorError: 21,
      meanAnchorError: 13,
      maxScaleError: 0.26,
      maxFrameJump: 12,
      maxRotationError: 1.5,
      maxWorldPositionError: 0.16,
      maxScaleLogError: 0.26,
      maxHeadJumpExcess: 0.04,
    },
    surfaceByMode: {
      'parametric-surface': 'cylinder',
      'direct-photometric': 'photometric-surfels',
    },
  },
  {
    name: 'crinkled snack pouch on busy moving background',
    create: () => createSnackPouchSequence({
      frameCount: 24,
      occlusionFrames: [9, 18],
      backgroundVariant: 'busy',
      backgroundSeed: 97,
    }),
    limits: {
      maxAnchorError: 23,
      meanAnchorError: 10,
      maxScaleError: 0.12,
      maxFrameJump: 12,
      maxRotationError: 0.85,
      maxWorldPositionError: 0.18,
      maxScaleLogError: 0.12,
      maxHeadJumpExcess: 0.05,
    },
    surfaceByMode: {
      'parametric-surface': 'plane',
      'direct-photometric': 'photometric-surfels',
    },
  },
];

export const reportReplayScenarios = [
  ...defaultReplayScenarios,
  ...realisticReplayScenarios,
];
