export const collectAnchorDetails = ({ anchorState, segmentationRefresh }) => {
  const metrics = anchorState?.metrics || {};

  return {
    keypointCount: metrics.keypointCount ?? 0,
    landmarkCount: metrics.landmarkCount ?? metrics.keypointCount ?? 0,
    activeLandmarkCount: metrics.activeLandmarkCount ?? metrics.keypointCount ?? 0,
    inactiveLandmarkCount: metrics.inactiveLandmarkCount ?? 0,
    objectOwnedLandmarks: metrics.objectOwnedLandmarks ?? 0,
    maskCoverage: metrics.maskCoverage ?? null,
    maskConfidence: metrics.maskConfidence ?? null,
    objectSupportMaskSource:
      metrics.currentObjectSupportMaskSource || metrics.objectSupportMaskSource || null,
    objectSupportMaskBounds: metrics.objectSupportMaskBounds || null,
    currentObjectSupportMaskBounds: metrics.currentObjectSupportMaskBounds || null,
    objectSupportMaskPreview:
      metrics.currentObjectSupportMaskPreview || metrics.objectSupportMaskPreview || null,
    objectSupportMaskConfidence: metrics.objectSupportMaskConfidence ?? null,
    keypointDensity: metrics.keypointDensity ?? null,
    backgroundRejected: metrics.backgroundRejected ?? 0,
    readiness: metrics.readiness || null,
    landmarkRefreshReason: metrics.landmarkRefreshReason || null,
    landmarkRefreshAdded: metrics.landmarkRefreshAdded ?? 0,
    landmarkRefreshTotal: metrics.landmarkRefreshTotal ?? 0,
    landmarkRefreshRejectedByMask: metrics.landmarkRefreshRejectedByMask ?? 0,
    landmarkRefreshCoverageBefore: metrics.landmarkRefreshCoverageBefore ?? null,
    landmarkRefreshCoverageAfter: metrics.landmarkRefreshCoverageAfter ?? null,
    landmarkRefreshCoverageCellCount: metrics.landmarkRefreshCoverageCellCount ?? null,
    landmarkRefreshOccupiedBefore: metrics.landmarkRefreshOccupiedBefore ?? null,
    landmarkRefreshOccupiedAfter: metrics.landmarkRefreshOccupiedAfter ?? null,
    segmentationRefreshReason: metrics.segmentationRefreshReason || null,
    segmentationRefreshFrame: metrics.segmentationRefreshFrame ?? null,
    segmentationRefreshStatus: segmentationRefresh?.status || 'idle',
    segmentationRefreshTrigger: segmentationRefresh?.trigger || null,
    segmentationRefreshOutcomeReason: segmentationRefresh?.outcomeReason || null,
    segmentationRefreshMaskSource: segmentationRefresh?.maskSource || null,
    templateKeypoints: metrics.templateKeypoints ?? metrics.keypointCount ?? 0,
    templateQuality: metrics.templateQuality ?? null,
    trackingRegion: metrics.trackingRegion || null,
    trackingSuccessRate: metrics.trackingSuccessRate ?? null,
    homographyInliers: metrics.homographyInliers ?? 0,
    affinePoseInliers: metrics.affinePoseInliers ?? 0,
    objectPoseInliers: metrics.objectPoseInliers ?? 0,
    reconstructionPoseInliers: metrics.reconstructionPoseInliers ?? 0,
    poseInliers: metrics.poseInliers ?? 0,
    poseModel: metrics.poseModel || null,
    poseSource: metrics.poseSource || null,
    poseRejectedReason: metrics.poseRejectedReason || null,
    poseSourceHoldReason: metrics.poseSourceHoldReason || null,
    targetClass: metrics.targetClass || null,
    surfaceModel: metrics.reconstructionPreview?.surface?.model || null,
    poseAverageResidual: metrics.poseAverageResidual ?? null,
    poseForeshortening: metrics.poseForeshortening ?? null,
    reconstructionState: metrics.reconstructionState || null,
    reconstructionRegion: metrics.reconstructionRegion || null,
    reconstructionReady: metrics.reconstructionReady ?? false,
    reconstructionFrames: metrics.reconstructionFrames ?? 0,
    reconstructionLandmarks: metrics.reconstructionLandmarks ?? 0,
    reconstructionDepthQuality: metrics.reconstructionDepthQuality ?? 0,
    reconstructionMapConfidence: metrics.reconstructionMapConfidence ?? 0,
    reconstructionAverageSupport: metrics.reconstructionAverageSupport ?? 0,
    reconstructionAverageReliability: metrics.reconstructionAverageReliability ?? 0,
    reconstructionGeometricConsistency: metrics.reconstructionGeometricConsistency ?? 0,
    reconstructionMatureLandmarks: metrics.reconstructionMatureLandmarks ?? 0,
    reconstructionDepthStatus: metrics.reconstructionDepthStatus || null,
    reconstructionDepthProvider: metrics.reconstructionDepthProvider || null,
    reconstructionDepthInferenceTime: metrics.reconstructionDepthInferenceTime ?? 0,
    reconstructionDepthFrameTimestamp: metrics.reconstructionDepthFrameTimestamp ?? null,
    reconstructionPreview: metrics.reconstructionPreview || null,
    reconstructionFailureReason: metrics.reconstructionFailureReason || null,
    reconstructionPoseRejectedReason: metrics.reconstructionPoseRejectedReason || null,
    surfaceCoverage: metrics.surfaceCoverage ?? null,
    surfacePrior: metrics.surfacePrior || null,
    surfaceLockedLandmarks: metrics.surfaceLockedLandmarks ?? 0,
    surfaceContourSegments: metrics.surfaceContourSegments ?? 0,
    surfaceCellCount: metrics.surfaceCellCount ?? 0,
    surfaceOccupiedCells: metrics.surfaceOccupiedCells ?? 0,
    silhouetteCoverage: metrics.silhouetteCoverage ?? null,
    contourFitResidual: metrics.contourFitResidual ?? null,
    landmarksInsideMask: metrics.landmarksInsideMask ?? 0,
    landmarksOutsideMask: metrics.landmarksOutsideMask ?? 0,
    occlusionState: metrics.occlusionState || null,
    surfaceGrowthAllowed: metrics.surfaceGrowthAllowed ?? false,
    surfaceOcclusionReason: metrics.surfaceOcclusionReason || null,
    poseOverlayCandidateSource: metrics.poseOverlayCandidateSource || null,
    poseOverlayCandidateScore: metrics.poseOverlayCandidateScore ?? null,
    poseAttachmentCandidateSource: metrics.poseAttachmentCandidateSource || null,
    poseAttachmentCandidateScore: metrics.poseAttachmentCandidateScore ?? null,
    posePositionCandidateSource: metrics.posePositionCandidateSource || null,
    posePositionCandidateScore: metrics.posePositionCandidateScore ?? null,
    posePositionRole: metrics.posePositionRole || null,
    posePositionReason: metrics.posePositionReason || null,
    poseNormalCandidateSource: metrics.poseNormalCandidateSource || null,
    poseNormalRole: metrics.poseNormalRole || null,
    poseNormalReason: metrics.poseNormalReason || null,
    normalPoseRejectedCandidates: metrics.normalPoseRejectedCandidates || {},
    poseCandidates: metrics.poseCandidates || [],
    rejectedPoseCandidates: metrics.rejectedPoseCandidates || {},
    recoveryAttempts: metrics.recoveryAttempts ?? 0,
    lostFrameCount: metrics.lostFrameCount ?? 0,
    lastFailureReason: metrics.lastFailureReason || null,
    lastFailureStage: metrics.lastFailureStage || null,
    lastUpdateMethod: metrics.lastUpdateMethod || null,
    processingTime: metrics.processingTime ?? 0,
    templateRegion: metrics.templateRegion || null,
    qualityState: metrics.qualityState || null,
    position: anchorState?.position || null,
    normal: anchorState?.normal || null,
    planarTransform: anchorState?.planarTransform || null,
  };
};
